2019-08-02 12:32:05,492  __init__/__init__.py:73  ip不可用__blog.csdn__>>https://116.115.209.88:20542HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-08-02 12:32:25,271  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:32:30,197  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:32:35,597  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:32:38,281  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:32:51,236  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:33:00,759  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:33:06,250  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:33:08,962  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:33:19,575  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:33:23,997  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:33:29,321  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:33:31,995  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:33:59,946  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:34:05,484  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:34:08,166  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:34:14,475  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:34:17,032  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:34:22,455  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:34:25,108  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:34:30,746  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:34:33,431  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:34:38,759  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:34:41,437  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:34:47,465  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:34:51,978  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:34:57,335  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:35:00,037  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:35:05,609  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:35:08,646  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:35:14,139  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:35:16,835  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:35:26,466  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:35:33,005  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:35:38,336  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:35:41,070  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:36:01,481  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:36:07,642  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:36:13,002  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:36:15,760  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:36:21,832  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:36:24,893  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:36:30,673  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:36:33,483  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:36:40,417  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:36:43,138  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:36:48,475  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:36:51,380  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:36:59,335  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:37:02,266  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:37:07,677  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:37:10,456  __init__/__init__.py:73  json解析错误__高德地图__>>：https://112.194.84.89:37489'NoneType' object has no attribute 'get'
2019-08-02 12:37:15,975  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:37:19,276  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:37:22,468  __init__/__init__.py:73  ip不可用__blog.csdn__>>https://112.194.84.89:37489HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0447DC90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-02 12:37:43,428  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:37:50,472  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
2019-08-02 12:38:00,696  __init__/__init__.py:73  ip不可用__blog.csdn__>>https://27.152.8.21:35183HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))
2019-08-02 12:38:09,553  __init__/__init__.py:73  json解析错误__高德地图__>>：https://27.152.8.21:35183'NoneType' object has no attribute 'get'
